# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 集豆
email: polybean@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  每天收集一颗豆子 属于你的丰收一定会萌芽
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: true
disqus_shortname: polybean

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
# https://github.com/jekyll/jekyll/issues/920
# collections:
#   tags:
#     output: true
# permalink: /tags/:tag.html

defaults:
  - scope:
      path: _posts
    values:
      layout: post
      comments: true

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-paginate
  - jekyll-feed
# applicable to jekyll-paginate-v2, not yet supported by github
# pagination:
#   enabled: true
#   per_page: 3
#   permalink: "/pages/:num/"
#   limit: 0
#   sort_field: date
#   sort_reverse: true

paginate: 5
paginate_path: /pages/:num/

albums:
  - 构建Docker镜像
